server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/calculation
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  jpa:
    properties:
      hibernate:
        show_sql: true

liteflow:
  enable: true
  rule-source: classpath*:/config/flow.xml
