server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddd-microservice-demo
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    redisson:
      file: classpath:redission.yml
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=600s

  jpa:
    properties:
      hibernate:
        show_sql: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml

liteflow:
  enable: true
  rule-source: classpath*:/config/flow.xml


data-dictionary:
  classPath: com.example.demo.domain.aggregate.DemoDataDictionaryType

logging:
  level:
    root: debug
