server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: base-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/base/**
          filters:
            - RewritePath=/api/base/(?<segment>.*), /$\{segment}
        - id: demo-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/demo/**
          filters:
            - RewritePath=/api/demo/(?<segment>.*), /$\{segment}

feign:
  client:
    config:
      callbackApiClient:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
